INSERT OR IGNORE INTO categories (class, name) VALUES
  ('Markkina', 'OMX Helsinki'),
  ('Markkina', 'OMX Stockholm'),
  ('Markkina', 'NYSE / NASDAQ'),
  ('Markkina', 'DAX'),
  ('Markkina', 'Kehittyvät markkinat'),
  ('Markkina', 'Kryptomarkkinat'),
  ('Toimiala', 'Teknologia'),
  ('Toimiala', 'Rahoitus'),
  ('Toimiala', 'Terveydenhuolto'),
  ('Toimiala', 'Teollisuus'),
  ('Toimiala', 'Kulutustavarat'),
  ('Toimiala', 'Energia'),
  ('Toimiala', 'Kiinteistöt'),
  ('Strategia', 'Arvosijoittaminen'),
  ('Strategia', 'Kasvusijoittaminen'),
  ('Strategia', 'Osinkosijoittaminen'),
  ('Strategia', 'Indeksisijoittaminen'),
  ('Strategia', 'Laatusijoittaminen'),
  ('Strategia', 'Käänneyhtiö'),
  ('Strategia', 'Vastuullisuus / ESG');